name: Test Expression
on:
  workflow_dispatch:

jobs:
  test_expression:
    name: Test Expression
    runs-on: ubuntu-latest
    steps:
      - run: echo start
      - run: echo ${{github.event_name}}
      - run: echo ${{github.event.inputs.continue-on-mongo-error}}
      - run: echo ${{ (github.event.inputs.continue-on-mongo-error != '' && fromJSON(github.event.inputs.continue-on-mongo-error)) || github.event_name == 'workflow_dispatch'}}
